export type {
  IStorageService,
  CreateUploadSessionRequest,
  CreateUploadSessionResponse,
  GetUploadPartUrlRequest,
  UploadPartRequest,
  RegisterPartRequest,
  CompleteUploadSessionRequest,
  CompleteUploadSessionResponse,
  GetReadUrlRequest,
  DeleteFileRequest,
  CreateTagRequest,
  AddTagToFileRequest,
  RemoveTagFromFileRequest,
  ListFileTagsRequest,
  ListFilesByTagRequest,
} from "@/ports/services/i-storage-service";
